# Generated by Django 5.1.7 on 2025-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("username", models.CharField(max_length=64, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("age", models.IntegerField(default=18, verbose_name="年龄")),
                (
                    "gender",
                    models.CharField(default="男", max_length=64, verbose_name="性别"),
                ),
                ("email", models.CharField(max_length=64, verbose_name="邮箱")),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
