# Generated by Django 5.1.7 on 2025-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manger",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "manger",
            },
        ),
    ]
